### PR TITLE
Allow text 2.0

### PR DESCRIPTION
**Pull request by tfausak**

### CODE REVIEW

**Comment by tfausak** [comment]
Thanks! Would you mind making a release or revision with these bounds?

**Comment by tchoutri** [comment]
Unfortunately I don't have maintainer rights on Hackage. Perhaps @maksbotan or @dmjio can help?

**Comment by dmjio** [comment]
I can make a release

**Comment by dmjio** [comment]
@tfausak @tchoutri https://hackage.haskell.org/package/servant-lucid-0.9.0.6

**Comment by tfausak** [comment]
Thank you!

**Pull request merged**
