### PR TITLE
Relax bounds: servant, servant-server

### PR DESCRIPTION
**Pull request by Tristano8**

### CODE REVIEW

**Comment by Tristano8** [comment]
Ci failures are caused by https://github.com/haskell-servant/servant/issues/1691

Once https://github.com/haskell/aeson/issues/1048 is merged and metadata revisions made for `servant` this should pass

**Comment by ysangkok** [comment]
Not all failures are caused by the aeson upgrade. Failures for the oldest builds are caused by lax lower bounds on GHC for servant (could be checked just by limiting base, though it is a bit weird):

```
Building library for servant-0.20..

src/Servant/Links.hs:10:14: error:
    Unsupported extension: QuantifiedConstraints
```

We should probably also raise the lower bound for servant, but since the builds will never work, they should be removed. Seems to me that the oldest GHC with QuantifiedConstraints is 8.6.

**Comment by ocharles** [comment]
Could we get a Hackage release with this, or a Hackage revision? Thanks!

**Comment by ysangkok** [comment]
@maksbotan I don't have the maintainer bit on this package, would it be possible for you to bump it?

**Comment by Bodigrim** [comment]
As a Hackage trustee I made a revision: https://hackage.haskell.org/package/servant-lucid-0.9.0.6/revisions/

**Pull request merged**
